### ISSUE TITLE
single items being printed get stuck

### ISSUE THREAD

**Issue by linuxgurugamer** [linuxgurugamer/Workshop#1]
where single﻿ items being printed would get stuck and not complete if the workshop lost focus﻿﻿﻿﻿﻿﻿.  The work around was to print two items, then come back when the first one was finished (according to the alarm).  You'd then cancel the﻿ queued item and the one being printed would then complete in a hurry.

This bug appears to be still present if the USI Constellation﻿ is installed.  I﻿ need to test further,  I didn't look to see if the bug was present if only WB was installed.  Or if both are present.

**Comment by PadroneSF** [comment]
I've replicated this issue with neither WBI or USI present, using Workshop 1.2.7.4.

I believe it's the presence of Kerbal Alarm Clock that is related to this issue.  I set up a test environment with only a few mods present (Such as HyperEdit, MechJeb and other such things.  No parts mods)  Hyperedited a mini-station with the workshop into orbit for testing.

(KAC NOT installed)  Able to do two production runs over 2+ items each.  Returning to the station after warping shows the messages that the items were produced, and the items were onboard the station.

Installed KAC into the existing game.  Setup a production run of two items.  Close workshop window, deleted the alarm.  Moved to the Tracking Station and warped for a few days time.  Returned to station.  No production messages.  First item was stuck in the queue with no progress made according to the UI.  Deleted queued up item and the 'stuck' item finished and appeared in inventory.

Queued up two more items, left the alarm set and moved to the Tracking Station. Warped past the alarm time.  Same as previous test, first item stuck in production,  Deleting queued up item let the production item finish up, show message and appear in inventory.

Exited game, removed KAC.  Repeated the "KAC NOT Installed" scenario and got the same results, production messages and both item in station inventory.

I can zip the gamedata file up and Dropbox it for you if you wish.

**Comment by PadroneSF** [comment]
Noticed on my way out that there is a 1.2.7.5.

I tried it and it appears to behave the same way.

**Comment by linuxgurugamer** [comment]
So, if I'm reading this correctly, if the KAC alarm is deleted, it stops working.  Is that a good summary of the problem?

**Comment by linuxgurugamer** [comment]
Also, there is now a setting to disable that, can you try disabling KAC for printing and try it again?  The setting is in the stock settings pages

**Comment by linuxgurugamer** [comment]
I've been able to replicate it.  Next time, what would be most important would be the log files.
It happens whenever the alarm is deleted, the mod starts getting ArgumentOutOfrange exceptions

**Comment by PadroneSF** [comment]
Oh, hai!  Good morning.  I just started testing. I'll get you the log files in a bit.

**Comment by linuxgurugamer** [comment]
Just released 1.2.7.6, fixes the bug

**Comment by PadroneSF** [comment]
That was quick!  I'll install it and check it out.

**Comment by PadroneSF** [comment]
Entered game, turned on the two KAC options under game difficulty.

Went to station, OSE window would not open upon clicking the button.  (Warning upon publishing the update needed, perhaps?)

Recovered station, put up a new one with Hyperedit. OSE Workbench window does not appear when clicking the button.  The button text does change, tho.

Started a new sandbox game, recreated station and Hyperedited to orbit.  Workbench menu still doesn't appear for me.

I *think* you can get the log [here]( https://www.dropbox.com/sh/tqz52cnp009ogsm/AAA6Fln9zcE303m2HMRgWK_ea?dl=0):

Dropbox looks like Google bought it since the last time I used it, and it's different.  Please let me know if you can't get the log.

**Comment by linuxgurugamer** [comment]
Please confirm that the bug is fixed

**Comment by PadroneSF** [comment]
It's still having issues when you use the alarms.  I queued up 8 items (4 < 20m each, and 2 < 2h each).

Coming back after the alarm showed me the first item still had 16m left.  None of the other things had printed.  Warping at that point had no effect on the progress displayed in the OSE window.

Deleting ALL the items in the queue resulted in the currently in production item being printed immediately.

Output_log.txt attached as a zip file.

[output_log.zip](https://github.com/linuxgurugamer/Workshop/files/2867100/output_log.zip)

**Comment by PadroneSF** [comment]
Further detailed testing:

OSE Test Run III - Feb 14

KSP: 1.6.1 (Win64) - Unity: 2017.1.3p1 - OS: Windows 7 Service Pack 1 (6.1.7601) 64bit 

Mods:
ClickThroughBlocker - 0.1.6.10
Filter Extensions - 3.2.2.15
Toolbar - 1.7.17.15
ToolbarControl - 0.1.6.20
Community Resource Pack - 1.1
ExtraplanetaryLaunchpads - 6.5
Firespitter - 7.9
KAS - 1.1.6876.38030
Kerbal Engineer Redux - 1.1.5.7
Kerbal Joint Reinforcement /L - 3.4.0.4
HyperEdit - 1.5.8
Kerbal Inventory System - 1.18.6971.42939
KSP-AVC Plugin - 1.2.0.7
SensiblePumpsCont - 1.2.6.3
Kerbal Alarm Clock - 3.10
VesselMover - 1.7.3
OSE Workshop - 1.2.7.7

Game Difficulty: 	Efficiency:	Print Requests create alarms: ON
			        Difficulty: 	Both printing and recycling alarms ON

Existing Station in orbit.

Print both a thermometer and an accelerometer.  Do not leave craft, do not close OSE window, warp to end of print jobs.  Both items print fine.  (Note: Alarms delete themselves)

Recycle  both items, leaving Recycler window open.  Warp to end of jobs.  Both items recycle fine.

Print both a thermometer and an accelerometer.  Do not close OSE window, leave to Tracking Station. Warp to end of print jobs.  Stored VesselID error still occurs.  Set KAC to delete on close, then close alarm.  “Fly” to the craft from the Tracking Station.  No “printed successfully” messages.   OSE workbench window opened to see that the thermometer has only 0.7% complete, Accelerometer still in queue.

Warping for several minutes has no progress indicated on the print job.  Delete the queued accelerometer jumps the thermometer progress to ~67% done.  Timer then continues to show printing progress.  Warp to end of printing, get success message, thermometer is in inventory.  (I believe this is the same behavior as before, but I didn’t keep those notes)

Recycle items, close recycler window.

Open OSE workbench window. Print both a thermometer and an accelerometer.  Close OSE window using the “X” button.  Leave to Tracking Station.  Warp to alarm.  Close alarm (again has the StoredID error).

Fly to craft, no printing success messages.  Open workbench window to see thermometer at 1% complete.  Delete the queued item, thermometer jumps to 65.5% done, warp, item prints.

Recycle the thermometer.

Go into settings, turn off all three Print Alarm settings.

Repeat print test where I don’t leave the station, all performs as desired.  Recycle items.

Repeat test where I leave the station without closing the OSE window.  Warp for an hour at the Tracking Station.  Return to craft.  Thermometer has printed, but the accelerometer is only at ~1%.  BUT!  The progress bar ticks along indicating progress.  Finish up, recycle everything.

Start another run, close OSE window with the “Close OSE window” button instead of the “X”.  Go to the Tracking Station, warp two hours, return to craft.  Thermometer print success message.  OSE window indicates 12.5% print completion for the accelerometer.  Progress bar continues, item prints after warping.   

Recycle items, exit KSP.  

Remove TriggerTech folder (KAC), start KSP and enter test environment.

Run last test again (Close OSE window and go to the Tracking Center… etc.)  When I return to the craft, I see success messages for both items, which are in the craft inventory.

Recycle items, exit KSP, re-install KAC, re-enter game.  Check KAC buttons in the OSE Settings window.   All are off.  

Repeat the same test.  Thermometer success print message shows when I go to the craft, accelerometer is at ~10% and printing.  (I.E. same as previous test using the same circumstances.)

Preliminary conclusion, just the presence of KAC may be causing issues, but I didn’t clear any files such as the MM cache, etc.

Please let me know if you'd like some different tests run, you have enough on your plate and I have the test environment on my disk, ready to go.

**Comment by linuxgurugamer** [comment]
A very extensive list of steps, thank you.
I will be able to look at this tomorrow

**Comment by linuxgurugamer** [comment]
Do you have the log file from the second set of tests?

**Comment by PadroneSF** [comment]
No, but I can run the second set of tests again.  (I didn't think about capturing the log file after each restart)

I'll do that tonight.

**Comment by linuxgurugamer** [comment]
The log can be useful to show me if any exceptions happen
Thanks

**Comment by linuxgurugamer** [comment]
the following:

> Coming back after the alarm showed me the first item still had 16m left. None of the other things had printed. Warping at that point had no effect on the progress displayed in the OSE window.

Does this mean you went to a different vessel?

**Comment by PadroneSF** [comment]
No, it was my test craft with the OSE workshop, the supply canisters for printing, a KIS container, a probe core, etc.  Only one vessel flying for this testing.  

I came back to it from the Tracking Center where I was warping to pass the time for the print jobs to finish.  (Have to go away from the test craft.  There are no problems when you stay with the craft as far I can tell.)

**Comment by PadroneSF** [comment]
I'll be doing the test run and posting the log in a bit, just got back from the symphony.

**Comment by PadroneSF** [comment]
Using the same test environment as before.  KAC is installed.  All three options for Workshop in Game Difficulty to do with KAC are selected/ON.

Flew to the craft from the Tracking Station.  Opened OSE workbench window.  Started printing both a thermometer and accelerometer.  (Both are 17m 18s complexity duration jobs)

Closed OSE window using the "X", went to the Tracking Station.  Alarm window shows a 34m, 27s alarm for the print job.  Warped for an hour of time, closed alarm, flew to craft.

Thermometer has 17m 13s left to end of print job.  Accelerometer is in queue.  Warping for 5m of time has no visible effect on the thermometer printing.  Deleted queued accelerometer.  Message for a successful print job shows on screen, thermometer is in Printing Lab seat inventory.

Recycled items left over from all prior printing.  Started another thermometer/accelerometer combo as before, except I left the OSE window open as I went to the Tracking Station.  

Warped for an hour, closed alarm, went to the craft from the Tracking Station.  Same results, thermometer has 17m 15s left.  Deleted accelerometer from queue, got the successful print message.

Quit game.  Log file attached.

[output_log Feb 25 2248hrs.zip](https://github.com/linuxgurugamer/Workshop/files/2871614/output_log.Feb.25.2248hrs.zip)

**Comment by linuxgurugamer** [comment]
Ok.  I've found one problem, so now it isn't nullref'ing on me.  It actually wasn't KAC itself, just some related code..
However, it also is not processing properly when not in the scene.

**Comment by linuxgurugamer** [comment]
I think I got it.  Hope to have a test DLL for you to test soon

**Comment by linuxgurugamer** [comment]
It's working now, but there is an alarm issue with the recycling (the alarm is not correct), once I get that fixed, I'll push out another beta

**Comment by linuxgurugamer** [comment]
Just pushed a release, please try it (1.2.7.9)

**Comment by PadroneSF** [comment]
Installed 1.2.7.10 by removing the old directory and dropping the new one into the same game folder.

**Conclusion:** There appears to be a slight issue with the recycle alarms and the menu window progress bar not matching, but you've squashed the main functional bug we've been chasing!

**Testing Details:** 

Launched existing game.  Checked to ensure all 3 alarm options are on in Game Difficulty settings.

Opened OSE window on existing craft in orbit.  Queued up a thermometer and accelerometer.  Left OSE window open and moved to the Tracking Station.  Warped to alarm.  Closed/deleted the alarm and warped for another 30 minutes.  Returned to craft,  Got completion messages for both items, and both items are in the craft's inventory.  <Cheers erupted from the Space Center at this point>

Set recycling run for both items, moved to Tracking Station.  Warped past alarm for a total of ~5 minutes.  Went back to craft and got recycle success messages for both items.

Set up a print run as before, with a closed OSE window.  This time I stayed with the craft and time warped.  Both success messages appeared, and both items were in inventory.  

Repeated last test with OSE window staying open.  Both success messages appeared when expected, alarm seemed to be on time.

Ran a recycle run on two items, keeping recycle window open and staying with craft.  Got the first success message when expected.  The alarm has 28s seconds left, but the progress bar has 11s left, and is not moving.  Then I realized the craft had run out of electric charge.  Warped to sunlight hitting the craft and everything completed as expected, with the alarm being pretty spot on.  So, actually, no problem!

Recycled a thermometer and left quickly to the Tracking station, I left the recycle window open.  Waited for alarm, closed/deleted it and returned to craft.  Success message and item is gone from inventory.  

Repeated for the accelerometer only with the Recycler window closed before going to the tracking station.  I think it said 11s on the recycler window, but the alarm had ~28s.  Otherwise, no problems.

Printed an experiment storage unit (Much  longer print time).  Set it up to recycle.  Noticed during this run the Base recycle time is 10m 11s according to the info in the window.  Set it up to recycle.  Progress timer has ~4m 25s, but the alarm says ~10m.  

Paused recycler and set up a run to recycle some tape.  Hover information on the item displayed in the Recycler Menu says 24s, the alarm that popped up says 54s. Clicked the start button and saw the progress bar start at 11s.  Timer ran down to 0, then on to negative numbers to finish up when the alarm says done.   (I noticed the progress bar went from "T- 1s" to saying "T - - 0s" and kept counting with two "-", making me think it was negative.  Picture of the double negative is attached)

![2019-02-17 12_42_24-ksp ose test](https://user-images.githubusercontent.com/11775210/52917599-125b0300-32b3-11e9-90ee-589ac2d5d11e.jpg)

**Comment by linuxgurugamer** [comment]
Thank you.  The alarm in KAC is set to the last item in the recycle queue, did you have more than one item in it?
The "T-" is text, the other "-" is probably a negative number as you say, the formatting would do that.
So the only significant things are the last two, recycling the experiment storage unit and the tape (tape really shouldn't be recycled).  The time issue with the accelerometer is probably the same thing as the next one.
I'll try to replicate and fix it tomorrow.
Thanks for a very detailed report, it's very helpful

**Comment by PadroneSF** [comment]
No, the last three recycle 'runs' were one item each, Accelerometer, Experiment Storage Unit and Tape.

**Comment by linuxgurugamer** [comment]
Ok, will look at this soon

**Comment by linuxgurugamer** [comment]
Found the problem, will release next beta soon

**Comment by linuxgurugamer** [comment]
Released the beta last night, please try it out

**Comment by PadroneSF** [comment]
Installed 1.2.7.11 by removing the old directory and dropping the new one into the existing game folder.

**Conclusion:**  It appears everything is working as designed now.  Good work, O tireless one!

**Testing Details:**

Ensured all three KAC alarm options for the Workshop are turned on in Game Settings.

Started printing thermometer (17m and 18s) and accelerometer (17m and 18s).  Closed OSE window, noted the KAC window says about 34m and 35s., went to the Tracking Station.  KAC window still shows about the right time.

Warped to alarm.  Alarm displays, and no longer has the error about the VesselID.  Clicked the 'Delete on close' and jumped to ship via alarm.  I see two message for successful prints, and the items are in inventory.

Setup another print run with an Experiment Storage Unit (1hr 53m 14s) and a SENTINEL telescope (5h, 46m 5s)  Alarm shows  the correct total time (1d, 1h 36m).  Closed OSE window and went to the Tracking Station.

Warped to alarm, clicked the 'delete on close', jumped to the station via KAC alarm.   Saw two 'printing completed' messages, both items in inventory.

Setup a recycle run for the four items.  ~35m.  left the Recycle window open, went to the Tracking Station.    I had to go back to the tracking station, the electric charge had run out while I was 'away'.  Warped again.  I noticed at the Tracking Station the alarm was counting down again.  It would appear returning to the ship reset the alarm.   Warped to alarm, returned to ship and saw the four 'finished' messages.  All four items were gone from inventory.
